### ISSUE TITLE
Incorrect fetching of Mapping rules from 3scale

### ISSUE THREAD

**Issue by azgabur** [3scale/threescale-wasm-auth#88] opened 2022-10-10 16:13 UTC
Metrics associated with mapping rules are fetched without system_name so a default "Hits" is used. The default "Hits" doesnt correspond with default "hits" in 3scale so every backend call results in 404 `<error code="metric_invalid">metric "Hits" is invalid</error>)` resulting in all traffic being rejected.

**Comment by pehala** [comment] 2022-10-11 07:11
That also means that custom metrics are not fetched correctly

**Comment by pehala** [comment] 2022-10-12 10:51
This problem was caused by two problems
1) Our configuration couldn't get parsed, due to missing api_backend field, which should not be required (Fixed by https://github.com/3scale-rs/straitjacket/pull/29)
2) As a fallback it tried to fetch mapping rules from a different endpoint, which sadly doesn't contain all the info required, this is fixed by a linked issue

**Closed as completed** 2022-10-25 09:24 UTC
